export const SCHOOLS: string[] = [
  // Power 4 Conferences
  "Alabama", "Arkansas", "Auburn", "Florida", "Florida State",
  "Georgia", "Georgia Tech", "Kentucky", "LSU", "Miami (FL)",
  "Mississippi State", "Missouri", "Ole Miss", "South Carolina",
  "Tennessee", "Texas A&M", "Vanderbilt",
  "Arizona", "Arizona State", "California", "Colorado", "Oregon",
  "Oregon State", "Stanford", "UCLA", "USC", "Utah",
  "Washington", "Washington State",
  "Boston College", "Clemson", "Duke", "Louisville", "NC State",
  "North Carolina", "Notre Dame", "Pittsburgh", "Syracuse",
  "Virginia", "Virginia Tech", "Wake Forest",
  "Baylor", "BYU", "Cincinnati", "Houston", "Iowa State",
  "Kansas", "Kansas State", "Oklahoma State", "TCU",
  "Texas", "Texas Tech", "UCF", "West Virginia",
  "Illinois", "Indiana", "Iowa", "Maryland", "Michigan",
  "Michigan State", "Minnesota", "Nebraska", "Northwestern",
  "Ohio State", "Penn State", "Purdue", "Rutgers", "Wisconsin",
  // Other major programs
  "Air Force", "Akron", "Alabama A&M", "Albany", "Appalachian State",
  "Army", "Ball State", "Boise State", "Bowling Green",
  "Buffalo", "Butler", "Central Michigan", "Charlotte",
  "Connecticut", "Davidson", "Dayton", "Delaware",
  "Drake", "Drexel", "East Carolina", "Eastern Michigan",
  "Elon", "Fairleigh Dickinson", "Fordham", "Fresno State",
  "Furman", "George Mason", "George Washington", "Gonzaga",
  "Grambling", "Hampton", "Hawaii", "Holy Cross", "Howard",
  "Idaho", "Jacksonville", "James Madison", "Kent State",
  "Liberty", "Louisiana Tech", "Marshall", "Memphis",
  "Middle Tennessee", "Montana", "Monmouth", "Murray State",
  "Nevada", "New Mexico", "New Mexico State", "Northern Iowa",
  "Ohio", "Old Dominion", "Portland State", "Rhode Island",
  "Richmond", "Sacred Heart", "Saint Mary's", "Sam Houston",
  "San Diego State", "San Jose State", "Seton Hall", "Southern Miss",
  "Stephen F. Austin", "Temple", "Texas State", "Toledo",
  "Towson", "Troy", "Tulane", "Tulsa", "UCONN", "UNLV",
  "UT San Antonio", "UTEP", "Villanova", "Western Kentucky",
  "Western Michigan", "William & Mary", "Xavier", "Yale",
].sort();
