/** Curated waitlist schools — Stanford first, then expand as needed. */
export const SCHOOLS: string[] = [
  "Stanford",
  "Yale",
  "Northwestern",
  "UCLA",
  "Cal Berkeley",
  "Iowa State",
  "Menlo College",
  "Saginaw Valley State",
  "Santa Clara",
  "Boston University",
  "University of South Dakota",
  "USC",
  "Michigan",
  "Columbia",
  "Indiana",
  "Purdue",
  "U Chicago",
  "Utah",
];
